# Generated by Django 5.0.1 on 2024-01-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Due_Date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Title',
            new_name='title',
        ),
    ]
